# -*- mode: python ; coding: utf-8 -*-
"""
PyInstaller spec file for PaddleOCR + PySide6 application.

PaddlePaddle 3.0.0 版本已重构模块结构，paddle.fluid 模块已移除。
"""

import sys
import os
from PyInstaller.utils.hooks import collect_data_files, collect_submodules

block_cipher = None

# 收集数据文件
datas = [
    ('src', 'src'),
    ('config.py', '.'),
]

# 尝试收集 paddle 和 paddleocr 的数据文件
try:
    datas += collect_data_files('paddleocr', include_py_files=False)
except Exception:
    pass

try:
    datas += collect_data_files('paddle', include_py_files=False)
except Exception:
    pass

try:
    datas += collect_data_files('shapely', include_py_files=False)
except Exception:
    pass

# PaddlePaddle 3.0 模块结构（不再使用 paddle.fluid）
hiddenimports = [
    # PaddlePaddle 3.0 核心
    'paddle',
    'paddle.base',
    'paddle.base.core',
    'paddle.base.framework',
    'paddle.base.executor',
    'paddle.inference',
    'paddle.framework',
    'paddle.framework.ir',
    'paddle.tensor',
    'paddle.device',
    'paddle.dataset',
    'paddle.reader',
    'paddle.distributed',
    
    # PaddlePaddle NN 模块
    'paddle.nn',
    'paddle.nn.layer',
    'paddle.nn.layer.layers',
    'paddle.nn.layer.activation',
    'paddle.nn.layer.conv',
    'paddle.nn.layer.norm',
    'paddle.nn.layer.linear',
    'paddle.nn.layer.pooling',
    'paddle.nn.layer.container',
    'paddle.nn.functional',
    'paddle.nn.initializer',
    'paddle.nn.utils',
    
    # PaddlePaddle 其他模块
    'paddle.optimizer',
    'paddle.optimizer.optimizer',
    'paddle.optimizer.lr',
    'paddle.optimizer.lr.scheduler',
    'paddle.loss',
    'paddle.metric',
    'paddle.autograd',
    'paddle.jit',
    'paddle.profiler',
    'paddle.amp',
    'paddle.quantization',
    'paddle.sparse',
    'paddle.linalg',
    'paddle.math',
    'paddle.io',
    'paddle.io.dataset',
    'paddle.io.loader',
    'paddle.io.sampler',
    'paddle._C_ops',
    'paddle._C_sot',
    
    # PaddleOCR 模块
    'paddleocr',
    'paddleocr.paddleocr',
    'paddleocr.ppocr',
    'paddleocr.ppocr.utils',
    'paddleocr.ppocr.utils.utility',
    'paddleocr.ppocr.utils.logging',
    'paddleocr.ppocr.utils.network',
    'paddleocr.ppocr.utils.e2e_utils',
    'paddleocr.ppocr.utils.e2e_utils.pgnet',
    'paddleocr.ppocr.post_processing',
    'paddleocr.ppocr.post_processing.db_postprocess',
    'paddleocr.ppocr.data',
    'paddleocr.ppocr.data.imaug',
    'paddleocr.ppocr.data.imaug.operators',
    'paddleocr.ppocr.data.dataset',
    'paddleocr.ppocr.predict_system',
    'paddleocr.ppocr.architecture',
    'paddleocr.tools',
    'paddleocr.tools.infer',
    'paddleocr.tools.infer.utility',
    
    # 关键依赖
    'shapely',
    'shapely.geometry',
    'shapely.geometry.polygon',
    'shapely.geometry.base',
    'shapely.ops',
    'shapely.lib',
    'pyclipper',
    'psutil',
    'scipy',
    'scipy.spatial',
    'scipy.spatial.qhull',
    'scipy.special',
    'scipy.sparse',
    'scipy.linalg',
    'scipy.ndimage',
    'scipy.optimize',
    'scipy.interpolate',
    'six',
    'lmdb',
    'lmdb.c',
    'pyyaml',
    'yaml',
    'tqdm',
    'tqdm.auto',
    'tqdm.std',
    'attrs',
    'attr',
    
    # 图像处理
    'cv2',
    'cv2.utils',
    'PIL',
    'PIL.Image',
    'PIL.ImageFile',
    'PIL._imaging',
    
    # 数值计算
    'numpy',
    'numpy.core',
    'numpy.core.multiarray',
    'numpy.core.umath',
    'numpy.fft',
    'numpy.linalg',
    'numpy.lib',
    'numpy.random',
    
    # 数据处理
    'pandas',
    'pandas._libs',
    'pandas._libs.tslibs',
    'pandas._libs.tslibs.base',
    'pandas.core',
    'pandas.core.api',
    'pandas.core.frame',
    'pandas.core.series',
    'pandas.core.arrays',
    'pandas.io',
    'pandas.io.excel',
    'pandas.io.formats',
    'openpyxl',
    'openpyxl.cell',
    'openpyxl.cell.cell',
    'openpyxl.styles',
    'openpyxl.styles.alignment',
    'openpyxl.styles.borders',
    'openpyxl.styles.fills',
    'openpyxl.styles.fonts',
    'openpyxl.styles.numbers',
    'openpyxl.workbook',
    'openpyxl.workbook.workbook',
    'openpyxl.worksheet',
    'openpyxl.worksheet.worksheet',
    'openpyxl.writer',
    'openpyxl.writer.excel',
    'openpyxl.utils',
    'openpyxl.utils.cell',
    
    # PySide6
    'PySide6',
    'PySide6.QtCore',
    'PySide6.QtGui',
    'PySide6.QtWidgets',
    'PySide6.support',

    # setuptools 59.8.0 — 正常分析，不 vendoring distutils
    'setuptools',
    'pkg_resources',

    # 标准库（distutils/packaging 由 PyInstaller 正常分析）
    'distutils',
    'distutils.core',
    'distutils.sysconfig',
    'packaging',
    'packaging.version',
    'packaging.specifiers',
    'packaging.requirements',

    # 标准库
    'logging',
    'logging.config',
    'logging.handlers',
    'pathlib',
    'tempfile',
    'shutil',
    'json',
    're',
    'collections',
    'collections.abc',
    'typing',
    'typing_extensions',
    'threading',
    'multiprocessing',
    'multiprocessing.context',
    'multiprocessing.pool',
    'multiprocessing.spawn',
    'concurrent',
    'concurrent.futures',
    'concurrent.futures.thread',
    'concurrent.futures.process',
    'queue',
    'functools',
    'itertools',
    'operator',
    'contextlib',
    'contextlib._contextlib',
    'warnings',
    'traceback',
    'copy',
    'copyreg',
    'pickle',
    'struct',
    'hashlib',
    'random',
    'math',
    'cmath',
    'time',
    'datetime',
    'calendar',
    'zoneinfo',
    'xml.etree.ElementTree',
    'csv',
    'argparse',
    'importlib',
    'importlib.abc',
    'importlib.machinery',
    'importlib.resources',
    'importlib.util',
    'site',
    'builtins',
    'os',
    'sys',
    'platform',
    'io',
    'abc',
    'dataclasses',
    'inspect',
    'dis',
    'codecs',
    'unicodedata',
    'string',
    'textwrap',
    'difflib',
    'hmac',
    'secrets',
    'statistics',
    'array',
    'ctypes',
    'mmap',
    'subprocess',
    'signal',
    'socket',
    'select',
    'selectors',
    'ssl',
    'urllib',
    'urllib.parse',
    'http',
    'http.client',
    'email',
    'email.mime',
    'html',
    'html.parser',
    'xml',
    'xml.dom',
    'xml.sax',
    'zipfile',
    'gzip',
    'bz2',
    'lzma',
    'tarfile',
    'configparser',
    'gettext',
    'locale',
    'runpy',
]

# 排除不需要的模块
excludes = [
    'tkinter',
    'matplotlib',
    'mpl_toolkits',
    'torch',
    'tensorflow',
    'keras',
    'torchvision',
    'transformers',
    'huggingface_hub',
    'datasets',
    'accelerate',
    'diffusers',
    'langchain',
    'openai',
    'anthropic',
    'boto3',
    'botocore',
    'awscli',
    'google.cloud',
    'googleapiclient',
    'grpc',
    'grpcio',
    'docker',
    'kubernetes',
    'ray',
    'dask',
    'distributed',
    'prefect',
    'airflow',
    'celery',
    'redis',
    'pymongo',
    'mysql',
    'psycopg2',
    'sqlalchemy',
    'django',
    'flask',
    'fastapi',
    'starlette',
    'uvicorn',
    'gunicorn',
    'werkzeug',
    'jinja2',
    'selenium',
    'playwright',
    'scrapy',
    'bs4',
    'beautifulsoup4',
    'httpx',
    'aiohttp',
    'pytest',
    '_pytest',
    'unittest',
    'unittest.mock',
    'coverage',
    'hypothesis',
    'black',
    'flake8',
    'pylint',
    'mypy',
    'isort',
    'tox',
    'nox',
    'jupyter',
    'jupyter_client',
    'jupyter_core',
    'ipython',
    'ipykernel',
    'notebook',
    'nbformat',
    'nbconvert',
    'Cython',
    'cython',
    'wheel',
    'pip',
    'sphinx',
    'docutils',
    'pygments',
]

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=['hooks'],
    hooksconfig={},
    runtime_hooks=['hooks/runtime_hook_paddle.py'],
    excludes=excludes,
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='handwritten-ocr',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=False,
    upx_exclude=[],
    name='handwritten-ocr',
)